// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class Test_class {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
        @Test
    public void test1() {
//Target text checkout
            driver.get("https://www.saucedemo.com/");
            driver.manage().window().setSize(new Dimension(945, 855));
            driver.findElement(By.id("user-name")).click();
            driver.findElement(By.id("user-name")).sendKeys("standard_user");
            driver.findElement(By.id("password")).click();
            driver.findElement(By.id("password")).sendKeys("secret_sauce");
            driver.findElement(By.id("login-button")).click();
            driver.findElement(By.id("add-to-cart-sauce-labs-backpack")).click();
            driver.findElement(By.xpath("//div[@id='shopping_cart_container']/a")).click();
            driver.findElement(By.id("checkout")).click();
            driver.findElement(By.id("first-name")).sendKeys("Vladyslav");
            driver.findElement(By.id("last-name")).sendKeys("Hrechykhin");
            driver.findElement(By.id("postal-code")).sendKeys("123456");
            driver.findElement(By.id("continue")).click();
            driver.findElement(By.id("finish")).click();
            if (driver.getPageSource().contains("Thank you for your order!") && driver.getPageSource().contains("Your order has been dispatched, and will arrive just as fast as the pony can get there!")) {
                System.out.println("Target text has been detected");
            }else{
                System.out.println("Target text is absent");
            };

    }
    //Items removal testing
    @Test
    public void test2(){
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(945, 855));
        driver.findElement(By.id("user-name")).click();
        driver.findElement(By.id("user-name")).sendKeys("standard_user");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("secret_sauce");
        driver.findElement(By.id("login-button")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-backpack")).click();
        driver.findElement(By.xpath("//div[@id='shopping_cart_container']/a")).click();
        if (driver.getPageSource().contains("Sauce Labs Backpack")){
            System.out.println("The chosen item has been added to the cart");
        }else{
            System.out.println("The chosen item hasn't been added to the cart. That's a bug");
        }
        driver.findElement(By.id("remove-sauce-labs-backpack")).click();
        if (driver.getPageSource().contains("Sauce Labs Backpack")){
            System.out.println("The chosen item hasn't been removed from the cart. That's a bug!");
        }else{
            System.out.println("The chosen item has been removed from the cart. Everything is ok.");
        }
        System.out.println("Thanks for teaching us! That has been a lot of pleasure and fun!");
    }
}
